OnlineStore/OnlineStore/Models/BasketViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineStore.Models
{
    public class BasketViewModel
    {
        public Guid Id { get; set; }
        public int CustomerId { get; set; }
        public decimal TotalCost { get; set; }
        public List<LineItemModel> BasketLineItems { get; set; }
       

    }
}

OnlineStore/OnlineStore/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Models;
using System.Net.Http;
using System.Net;
using OnlineStore.Common;
using OnlineStore.Contracts;
using System.Net.Http.Formatting;

namespace OnlineStore.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        //
        // GET: /Basket/

        private readonly IBasketManager basketMgr;

        /// <summary>
        /// Initializes a new instance of the <see cref="BasketController"/> class.
        /// </summary>
        /// <param name="basketmgr">The basketmgr.</param>
        public BasketController(IBasketManager basketmgr)
        {
            this.basketMgr = basketmgr;
        }

      
   
        public ActionResult Checkout(Dictionary<string,object> model)
        {
            if (Convert.ToBoolean(model["PayLater"]))
            {
                RedirectToAction("Index", "PayLater");
            }
            if (Convert.ToBoolean(model["PayNow"]))
            { 
                RedirectToAction("Index", "PayNow"); 
            }

            return View(model);
            //return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            HomeViewModel model = null;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            int customerId = 0;

            if (Session["User"] != null)
            {
                var userInfo = Session["User"] as UserCredentials;

                customerId = userInfo.CustomerId;
            }

            var basket = this.basketMgr.GetBasket(cart.ShoppingCartId, customerId);

            if (basket.BasketName == null)
            {
                Session["TotalAmount"] = null;
                return View(model);
            }

            model = new HomeViewModel
            {
                BasketViewModel = new BasketViewModel
                {
                    CustomerId = basket.CustomerId,
                    TotalCost = Convert.ToDecimal(basket.Amount)
                },
                ItemModel = basket.BasketItems.Select(i => new ItemModel
                {
                    Id = i.ItemId,
                    ItemName = i.ItemName,
                    Image = i.ImagePath,
                    Unit = i.Unit,
                    Price = i.Price,
                    Quantity = i.Quantity
                }).ToArray()

            };

            Session["TotalAmount"] = Convert.ToDecimal(basket.Amount);
            return View(model);
        }


        public ActionResult AddItem(int itemId, int quantity)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            Basket basket = new Basket();

            basket.BasketName = cart.ShoppingCartId;

            if (Session["User"] != null)
            {
                var userInfo = Session["User"] as UserCredentials;

                if (userInfo != null)
                {
                    basket.CustomerId = userInfo.CustomerId;
                }
            }

            basket.BasketItems = new[] { new Item { ProductId = itemId, Quantity = quantity } };

            this.basketMgr.AddItem(basket);

            return RedirectToAction("Index");
        }

        public ActionResult Empty()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            this.basketMgr.EmptyBasket(cart.ShoppingCartId);
            return RedirectToAction("Index");
        }


        public ActionResult AddToShoppingList(int itemId)
        {
            int customerId = 0;
            if (Session["User"] != null)
            {
                var userInfo = Session["User"] as UserCredentials;

                customerId = userInfo.CustomerId;
            }

            var res = this.basketMgr.AddToShoppingList(customerId, itemId);

            string response = res ? "Item added to Shopping List" : "Error in adding item to shopping list";

            return Content(response);
        }
    }
}

OnlineStore/OnlineStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Models;
using OnlineStore.Common;
using System.Net.Http;
using System.Net;

namespace OnlineStore.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        //
        // GET: /Store/

        private readonly IBasketManager basketManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="StoreController"/> class.
        /// </summary>
        /// <param name="basketMgr">The basket MGR.</param>
        public StoreController(IBasketManager basketMgr)
        {
            basketManager = basketMgr;
        }


        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var items = new List<ItemModel>();
            HttpClient client = new HttpClient();
            var response = client.GetAsync(string.Format("http://localhost:87/service/api/MyCart")).Result;

            if (response != null && response.StatusCode == HttpStatusCode.OK)
            {
                var masterProducts = response.Content.ReadAsAsync<OnlineStore.Contracts.Product[]>().Result;
                if (masterProducts != null)
                {
                    items = masterProducts.Select(p => new ItemModel
                    {
                        Id = p.ProductId,
                        ItemName = p.ProductName,
                        Image = string.Concat("../../Images/", p.ImagePath.Trim()),
                        Price = p.Price,
                        Unit = p.Unit
                    }).ToList();
                }
            }
            return View(items);
        }

        /// <summary>
        /// Views the specified identifier.
        /// </summary>
        /// <param name="Id">The identifier.</param>
        /// <returns></returns>
        public ActionResult View(int Id)
        {
            var items = new List<ItemViewModel>();
            HttpClient client = new HttpClient();
            var response = client.GetAsync(string.Format("http://localhost:87/Service/api/MyCart")).Result;

            if (response != null && response.StatusCode == HttpStatusCode.OK)
            {
                var masterProducts = response.Content.ReadAsAsync<OnlineStore.Contracts.Product[]>().Result;
                if (masterProducts != null)
                {
                    items = masterProducts.Select(p => new ItemViewModel
                    {
                        Id = p.ProductId,
                        Name = p.ProductName,
                        ImagePath = string.Concat("../../Images/", p.ImagePath.Trim()),
                        Price = p.Price,
                        Unit = p.Unit
                    }).ToList();
                }
            }

            var itemViewModel = items.FirstOrDefault(k => k.Id == Id);
            return View(itemViewModel ?? new ItemViewModel());
        }

        /// <summary>
        /// Searches the specified kind.
        /// </summary>
        /// <param name="kind">The kind.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Search(string kind)
        {
            var items = new List<ItemModel>();
            HttpClient client = new HttpClient();
            var response = client.GetAsync(string.Format("http://localhost:87/Service/api/MyCart")).Result;

            if (response != null && response.StatusCode == HttpStatusCode.OK)
            {
                var masterProducts = response.Content.ReadAsAsync<OnlineStore.Contracts.Product[]>().Result;
                if (masterProducts != null)
                {
                    items = masterProducts.Select(p => new ItemModel
                    {
                        Id = p.ProductId,
                        ItemName = p.ProductName,
                        Image = string.Concat("../../Images/", p.ImagePath.Trim()),
                        Price = p.Price,
                        Unit = p.Unit
                    }).ToList();
                }
            }

            var results = items.Where(k => k.ItemName.Equals(kind, StringComparison.OrdinalIgnoreCase));

            return View("Index", results);
        }

    }
}

OnlineStore/OnlineStore/Views/Store/CartSummary.cshtml
@{
    ViewBag.Title = "CartSummary";
}

<h2>CartSummary</h2>

OnlineStore/OnlineStore/Views/Store/Index.cshtml
@model  IEnumerable<OnlineStore.Models.ItemModel>
@{
    ViewBag.Title = "Store Online Purchase";
    
}
<form method="get" action="/Store/Search">
<table>
    <tr>
        <th>
            <i>I am Looking for : </i>
        </th>
        <td>
            <input type="text" id="kind" name="kind" style="width:400px">
        </td>
        <td>
            <input type="submit" />
        </td>
    </tr>
</table>
</form>
<br />
<br />



<table>
    <tr>
        <td>
            <p class="button">
                @Html.ActionLink("View My Basket", "Index", "Basket")
            </p>
        </td>
        <td>
            <p class="button">
                @Html.ActionLink("View My Shopping List", "Index", "Basket")
            </p>
        </td>
    </tr>
    <tr>
        <td>
            <div id="addedShoppingList">
            </div>
        </td>
    </tr>
</table>
<table id="tbroot" style="border:solid; border-width:thin; ">
    <tr>
        <td>
            <table id="tbitems">
                <thead >
                    <tr>
                        <th style="width:200px">
                            Image
                        </th>
                        <th style="width:200px">
                            ItemName
                        </th>
                        <th style="width:200px">
                            Price
                        </th>
                        <th style="width:200px">
                            Unit
                        </th>
                        <th>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img height=40 width=40 src=@item.Image />
                            </td>
                            <td>
                                <div id="@("lblitem_" + item.Id)">@item.ItemName</div>
                                <input type="hidden" id="hdnItemId" value="@item.Id" />
                            </td>
                            <td>
                                <div id="@("lblprice_" + item.Id)">@item.Price</div>
                            </td>
                            <td>
                                <label id="@("lblunit_" + item.Id)">@item.Unit</label>
                            </td>
                            <td style="width:200px">
                                <p class="button">
                                    @Html.ActionLink("Add to Basket", "AddItem", "Basket", new { itemId = item.Id, quantity = 1 }, "")
                                </p>
                            </td>
                            @*<td>
                                    <input class="button" type="button" name="btnAddToShoppingList" id="btnAddToShoppingList" value="Add to Shopping List"
                                            onclick="javascript:AddToShoppingList(@item.Id);" />
                                </td>*@
                        </tr>
                    }
                </tbody>
            </table>
        </td>
    </tr>
</table>


<script type="text/javascript">
    function AddToShoppingList(val) {
        $.get('/Basket/AddToShoppingList', { itemId: val }, function (data) {
            $('#addedShoppingList').html(data);

        });
    }
</script>
<script src="../../Scripts/jquery-1.6.2.js" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.6.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../../Scripts/StoreOnline.js"></script>

OnlineStore/OnlineStore/Views/Store/Search123.cshtml
@*@model  StoreOnLineWeb.Models.ItemModel[]
@{
    ViewBag.Title = "Store Online Purchase";
    
     //var webGrid = new WebGrid(source: Model,
     //   rowsPerPage: 5,
     //   canPage: true,
     //   canSort: false);
}
<link href="../../Content/Web-GridStyles.css" rel="stylesheet" type="text/css" />

<form method="get" action="/Store/Search">
<table>
<tr>
<th><i>I am Looking for : </i></th><td><input type=text id="kind" name="kind"></td><td><input type=submit /></td></tr></table>
</form>
<br />
<br />

<table>
<tr>
<td><table>
<thead>
<tr>
<td></td>
<th>Image</th>
<th>Item Name</th>
<th>Price</th>
<th>Unit</th>
<th>Qty</th>
<th></th>
</tr></thead>
<tbody>
@foreach (var item in Model)
{
    <tr>
    <td>@Html.ActionLink("Detail", "View", new { item.Id},null)</td>
    <td><img height=40 width=40  src=@item.Image /></td>    
    <td>@item.ItemName</td>
    <td>@item.Price</td>
    <td>@item.Unit</td>    
    <td><input type="text" id="@item.Id" value=1  style="width:20px"/></td>
    <td>
    <a href=@Url.Action("Index","Store")>
                    <img src=@Url.Content("../../Images/Button/add_on.gif") /></a>
    @*<img src="../../Images/Button/add_on.gif" onclick="fun()" />*@</td>
    </tr>    
}
<scri 
fun
</tbody>
</table>
</td>
<td>
<h3>Basket Items List</h3>
<Input type=submit name="cmdCheckOut" value="Check Out" style="width:100px"></button>
</td>
</tr>
</table>







@*<div id="order-content">
    <table>
        <tbody>
            <tr>
                <td>
                    @webGrid.GetHtml(
                        headerStyle: "webgrid-header",
                        footerStyle: "webgrid-footer",
                        alternatingRowStyle: "webgrid-alternating-row",
                        rowStyle: "webgrid-row-style",
                        selectedRowStyle: "webgrid-selected-row",
                        displayHeader: true,
                        columns: webGrid.Columns(
                            webGrid.Column(columnName: "Id", header: "Order #"),
                            webGrid.Column(columnName: "ItemName", header: "Order Date"),
                            webGrid.Column(columnName: "Price", header: "# Of Units"),
                            webGrid.Column(columnName: "Unit", header: "Order Value ($)")))
                </td>
            </tr>
        </tbody>
    </table>
</div>
*@

@section Sidebar {
    <div id="sidebar">
        <p>
        </p>
        <h3>
            Customer Related Services</h3>
        <ul>
            <li><a href="#">Call Customer</a></li>
            <li><a href="#">Connect RDP</a></li>
            <li><a href="#">Show Reports</a></li>
            <li><a href="#">View Orders</a></li>
            <li><a href="#">Finalize Reports</a></li>
        </ul>
    </div>
    }
*@

OnlineStore/OnlineStore/Views/Store/View.cshtml
@model OnlineStore.Models.ItemViewModel
@{
    ViewBag.Title = "Product Detailed View";
}

<h2>Product Detailed View</h2>

<table>
<tr>
<td>
<table>
<tr>
<td><img src=@Model.ImagePath /></td>
</tr>
</table>
</td>
<td>
<table>
<tr><td>Name</td><td><div id="div_item">@Model.Name</div></td></tr>
<tr><td>Price</td><td><div id="div_price">@Model.Price</div></td></tr>

<tr><td>Quantity</td><td><table><tr><td>
<div style='float:left'><input type='button' name='btnMinusQty' id='btnMinusQty' value='-' /></div></td><td>
<div id="div_qty" style='float:left;width:50px;' align='center'>1</div></td><td>
<div style="float:left"><input type='button' name='btnAddQty' id='btnAddQty' value='+' /></div></td></tr></table>
</td>
</tr>

<tr><td>Unit</td><td><div id="div_unit")>@Model.Unit</div></tr>
<tr><td>Description</td><td></td></tr>
<tr><td colspan=2>@Model.Description</td></tr>
<tr><td colspan=2 align="right"><input type='button' name='btnBack' id='btnBack' value='     Back     '  onclick="javascript:history.back()" /><input type='button' name='btnAddCart' id='btnAddCart' value='Add to Cart'  /> </td></tr>

</table>
</td>
</tr>
</table>
<input type='hidden' id="hid_Id" value=@Model.Id />
<script type="text/javascript" src="../../Scripts/StoreOnline.js"></script>